[package]
name = "perfectseries"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.10"
pyo3 = { version = "0.21", features = ["extension-module"] }
